name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry install
    - name: Lint with flake8
      run: |
        poetry run python -m autoflake --in-place --remove-all-unused-imports --remove-unused-variables --recursive giwerm
        poetry run python -m isort giwerm
        poetry run python -m black --line-length=119 giwerm
    - name: Test with pytest
      run: |
        poetry run python -m pytest --durations=0 --cov=giwerm tests
